// Mock data for Traveloop frontend
// Uses Unsplash Source API for real destination images

export const DESTINATIONS = [
  {
    id: 'dest-1',
    city: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
    category: 'Culture',
    tagline: 'Where time moves like incense smoke',
    description: 'Ancient temples, bamboo forests, and geisha districts hidden in golden morning mist.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    rating: 4.9,
    avgCost: 120,
    tags: ['temples', 'culture', 'zen', 'cherry blossoms'],
    bestTime: 'Mar–May, Oct–Nov',
  },
  {
    id: 'dest-2',
    city: 'Santorini',
    country: 'Greece',
    continent: 'Europe',
    category: 'Beach',
    tagline: 'White curves against endless blue',
    description: 'Caldera views, volcanic beaches, and sunsets that feel like the world is ending beautifully.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    rating: 4.8,
    avgCost: 180,
    tags: ['beach', 'sunset', 'islands', 'romance'],
    bestTime: 'Jun–Sep',
  },
  {
    id: 'dest-3',
    city: 'Patagonia',
    country: 'Argentina',
    continent: 'South America',
    category: 'Adventure',
    tagline: 'Where the earth speaks in silence',
    description: 'Glaciers, condors, and granite towers at the edge of the known world.',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    rating: 4.9,
    avgCost: 95,
    tags: ['hiking', 'glaciers', 'nature', 'adventure'],
    bestTime: 'Nov–Mar',
  },
  {
    id: 'dest-4',
    city: 'Marrakech',
    country: 'Morocco',
    continent: 'Africa',
    category: 'Culture',
    tagline: 'A labyrinth of senses and stories',
    description: 'Medinas alive with colour, fragrance of spices, and rooftop terraces at dusk.',
    image: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80',
    rating: 4.7,
    avgCost: 65,
    tags: ['souks', 'culture', 'food', 'architecture'],
    bestTime: 'Mar–May, Sep–Nov',
  },
  {
    id: 'dest-5',
    city: 'Reykjavik',
    country: 'Iceland',
    continent: 'Europe',
    category: 'Adventure',
    tagline: 'Land of fire, ice, and northern lights',
    description: 'Geysers, midnight sun, aurora borealis, and geothermal pools under the stars.',
    image: 'https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800&q=80',
    rating: 4.8,
    avgCost: 220,
    tags: ['aurora', 'geysers', 'nature', 'unique'],
    bestTime: 'Jun–Aug, Dec–Feb',
  },
  {
    id: 'dest-6',
    city: 'Hoi An',
    country: 'Vietnam',
    continent: 'Asia',
    category: 'Culture',
    tagline: 'Lantern light on ancient waters',
    description: 'Ancient town glowing with lanterns, tailor shops, and river boats at golden hour.',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
    rating: 4.8,
    avgCost: 45,
    tags: ['lanterns', 'food', 'culture', 'cycling'],
    bestTime: 'Feb–Apr, Aug–Oct',
  },
  {
    id: 'dest-7',
    city: 'Amalfi Coast',
    country: 'Italy',
    continent: 'Europe',
    category: 'Beach',
    tagline: 'Cliff-side dreams and lemon groves',
    description: 'Pastel villages cascading to turquoise seas, slow lunches, and limoncello at sunset.',
    image: 'https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=800&q=80',
    rating: 4.9,
    avgCost: 200,
    tags: ['coast', 'food', 'romantic', 'scenic'],
    bestTime: 'May–Sep',
  },
  {
    id: 'dest-8',
    city: 'Queenstown',
    country: 'New Zealand',
    continent: 'Oceania',
    category: 'Adventure',
    tagline: 'The adventure capital of the world',
    description: 'Fjords, bungee jumps, and mountains that look like they were painted by hand.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    rating: 4.8,
    avgCost: 140,
    tags: ['adventure', 'mountains', 'fjords', 'extreme'],
    bestTime: 'Dec–Feb, Jun–Aug',
  },
]

export const MOOD_OPTIONS = [
  { id: 'explore', label: 'Explore', icon: '🧭', desc: 'Discover hidden corners' },
  { id: 'relax', label: 'Relax', icon: '🌊', desc: 'Slow down and breathe' },
  { id: 'adventure', label: 'Adventure', icon: '⛰️', desc: 'Push your limits' },
  { id: 'culture', label: 'Culture', icon: '🏛️', desc: 'Soak in history & art' },
  { id: 'food', label: 'Food', icon: '🍜', desc: 'Eat your way through' },
  { id: 'romance', label: 'Romance', icon: '✨', desc: 'Moments made for two' },
]

export const ACTIVITY_CATEGORIES = [
  { id: 'culture', label: 'Culture & History', icon: '🏛️', color: '#D9C3A5' },
  { id: 'food', label: 'Food & Dining', icon: '🍜', color: '#FCA5A5' },
  { id: 'nightlife', label: 'Nightlife', icon: '🌙', color: '#A78BFA' },
  { id: 'adventure', label: 'Adventure', icon: '⛰️', color: '#6EE7B7' },
  { id: 'photography', label: 'Photography', icon: '📷', color: '#6EA8FE' },
  { id: 'wellness', label: 'Wellness', icon: '🧘', color: '#FCD34D' },
]

export const SAMPLE_ACTIVITIES = {
  culture: [
    { id: 'a1', name: 'Fushimi Inari Shrine', category: 'culture', duration: 120, cost: 0, rating: 4.9, desc: 'Walk through 10,000 vermillion torii gates winding up a mountain.' },
    { id: 'a2', name: 'Arashiyama Bamboo Grove', category: 'culture', duration: 60, cost: 0, rating: 4.8, desc: 'A surreal path through towering bamboo at dawn.' },
    { id: 'a3', name: 'Kinkaku-ji Temple', category: 'culture', duration: 90, cost: 5, rating: 4.9, desc: 'The golden pavilion reflected in mirror-still water.' },
  ],
  food: [
    { id: 'a4', name: 'Nishiki Market', category: 'food', duration: 90, cost: 20, rating: 4.7, desc: 'Five-block market known as "Kyoto\'s kitchen".' },
    { id: 'a5', name: 'Sake Brewery Tour', category: 'food', duration: 120, cost: 35, rating: 4.6, desc: 'Traditional sake tasting in a 200-year-old brewery.' },
    { id: 'a6', name: 'Matcha Ceremony', category: 'food', duration: 60, cost: 28, rating: 4.8, desc: 'Traditional tea ceremony in a zen garden teahouse.' },
  ],
  adventure: [
    { id: 'a7', name: 'Mount Kurama Hike', category: 'adventure', duration: 180, cost: 5, rating: 4.7, desc: 'Forest trail with spiritual shrines and mountain views.' },
    { id: 'a8', name: 'Cycling the Old City', category: 'adventure', duration: 180, cost: 15, rating: 4.8, desc: 'Pedal through temple-lined streets and local neighbourhoods.' },
  ],
  photography: [
    { id: 'a9', name: 'Sunrise at Maruyama', category: 'photography', duration: 90, cost: 0, rating: 4.9, desc: 'Cherry blossoms and lanterns at first light.' },
    { id: 'a10', name: 'Gion Nightwalk', category: 'photography', duration: 120, cost: 0, rating: 4.8, desc: 'Spot geishas in the ancient entertainment district.' },
  ],
}

export const MOCK_TRIPS = [
  {
    id: 'trip-1',
    name: 'Golden Hour in Japan',
    destination: 'Kyoto, Japan',
    startDate: '2025-10-12',
    endDate: '2025-10-22',
    mood: 'culture',
    budgetTotal: 2500,
    budgetSpent: 1840,
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    status: 'upcoming',
    stops: [
      { id: 's1', dayNumber: 1, placeName: 'Fushimi Inari', placeType: 'Shrine', notes: 'Start at sunrise', position: 0 },
      { id: 's2', dayNumber: 1, placeName: 'Nishiki Market', placeType: 'Market', notes: 'Lunch here', position: 1 },
      { id: 's3', dayNumber: 2, placeName: 'Arashiyama', placeType: 'Nature', notes: 'Bamboo groove + monkey park', position: 0 },
      { id: 's4', dayNumber: 3, placeName: 'Kinkaku-ji', placeType: 'Temple', notes: 'Book tickets in advance', position: 0 },
    ],
    expenses: [
      { id: 'e1', category: 'Accommodation', description: 'Ryokan 5 nights', amount: 750, date: '2025-10-12' },
      { id: 'e2', category: 'Food', description: 'Daily dining budget', amount: 420, date: '2025-10-13' },
      { id: 'e3', category: 'Transport', description: 'JR Pass', amount: 380, date: '2025-10-12' },
      { id: 'e4', category: 'Activities', description: 'Temples & tours', amount: 180, date: '2025-10-14' },
      { id: 'e5', category: 'Shopping', description: 'Ceramics & gifts', amount: 110, date: '2025-10-18' },
    ],
  },
  {
    id: 'trip-2',
    name: 'Aegean Blue',
    destination: 'Santorini, Greece',
    startDate: '2025-07-08',
    endDate: '2025-07-16',
    mood: 'relax',
    budgetTotal: 3200,
    budgetSpent: 3200,
    coverImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    status: 'completed',
    stops: [],
    expenses: [
      { id: 'e6', category: 'Accommodation', description: 'Cave suite hotel', amount: 1600, date: '2025-07-08' },
      { id: 'e7', category: 'Food', description: 'Seaside restaurants', amount: 680, date: '2025-07-09' },
      { id: 'e8', category: 'Transport', description: 'Flights + ferry', amount: 720, date: '2025-07-08' },
      { id: 'e9', category: 'Activities', description: 'Sunset cruise', amount: 200, date: '2025-07-12' },
    ],
  },
  {
    id: 'trip-3',
    name: 'End of the World',
    destination: 'Patagonia, Argentina',
    startDate: '2026-01-15',
    endDate: '2026-01-28',
    mood: 'adventure',
    budgetTotal: 4000,
    budgetSpent: 0,
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    status: 'planning',
    stops: [],
    expenses: [],
  },
]
